version: '3.8'

services:
  n8n:
    image: n8nio/n8n:latest
    environment:
      - N8N_EMAIL_MODE=smtp
      - N8N_SMTP_HOST=je_smtp_server
      - N8N_SMTP_PORT=je_smtp_poort
      - N8N_SMTP_USER=je_smtp_gebruiker
      - N8N_SMTP_PASS=je_smtp_wachtwoord
      - N8N_SMTP_SENDER=afzender_emailadres
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_USER=n8n
      - DB_POSTGRESDB_PASSWORD=n8n_password
      - NODE_FUNCTION_ALLOW_EXTERNAL=pg
      - PORT=5555
    ports:
      - "5555:5555"
    depends_on:
      - postgres

  postgres:
    image: postgres:12
    environment:
      - POSTGRES_DB=n8n
      - POSTGRES_USER=n8n
      - POSTGRES_PASSWORD=n8n_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
